### PR TITLE
RespaAdmin: Render equipment layout in single/double column

### PR DESCRIPTION
**Pull request by urshala**
* Render the equipments in a single column for mobile devices and two columns for others
* Order the equipments first by name instead of category

Screenshot 2022-03-17 at 13 03 54

### CODE REVIEW

**Comment by tomijarvi** [comment]
Added @juhakujala

**Review by tomijarvi — COMMENTED** [review]
Can we change that it uses two columns? The one-column stretch quite much the page. example: https://codepen.io/juhakujala/pen/LYexGyO

**Comment by urshala** [comment]
> 

Changed to use single column for mobile devices and double column for others. 


Screenshot 2022-03-25 at 13 46 21

**Review by tomijarvi — APPROVED** [review]
Nice! 💪

**Pull request merged**
